server:
  port: 8088

spring:
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: my-group
      auto-offset-reset: earliest
      properties:
        spring.json.trusted.packages: me.bdv.user.api.dto
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      retries: 3
      acks: all
      properties:
        batch.size: 16384
        linger.ms: 1

kafka:
  topic:
    userCash: user-cash